Feature/controller
f-lab-edu/jobhub pull request #3
Opened 2023-12-28 10:07 UTC by yunju2

2023-12-28 13:52 UTC, f-lab-lyan commented on app/build.gradle
> +    compileOnly 'org.projectlombok:lombok'
https://plugins.gradle.org/plugin/io.freefair.lombok

2023-12-28 13:54 UTC, f-lab-lyan commented on app/build.gradle
> +dependencies {
각각의 dependency 들의 순서를 맞춰보면 어떨까 싶네요.

2023-12-28 13:55 UTC, f-lab-lyan commented on app/src/main/java/com/jobhub/controller/dto/CareerCategoryResponse.java
> +@Getter
@Builder @Getter 에 대해서 얘기해보죠. 어떤 의도인지에 대해서

2023-12-28 14:01 UTC, f-lab-lyan commented on app/src/main/java/com/jobhub/controller/RecruitmentController.java
> +                                                             @RequestParam(required = false) String locations,
locations를 enum으로 정의한 경우, 어떤 문제가 생길 수 있을까요?

2023-12-28 14:07 UTC, f-lab-lyan requested changes
테스트 코드를 작성해 주시면 좋을 것 같아요.

2024-01-02 07:25 UTC, f-lab-lyan commented on app/src/main/java/com/jobhub/controller/FilterController.java
> +import com.jobhub.controller.dto.*;
import가 협쳐지지 않도록 intellij설정을 변경하는게 어떨까 싶네요.

2024-01-03 08:34 UTC, yunju2 commented on app/build.gradle
> +    compileOnly 'org.projectlombok:lombok'
알려주신대로 수정했습니다!

2024-01-03 08:34 UTC, yunju2 commented on app/build.gradle
> +dependencies {
네 알겠습니다.! 수정했습니다.

2024-01-03 08:37 UTC, yunju2 commented on app/src/main/java/com/jobhub/controller/RecruitmentController.java
> +                                                             @RequestParam(required = false) String locations,
만약 location이 추가되거나 수정이되면, enum에도 추가,수정해야해서 서버가 새로 배포되어야해서 안좋습니다.

2024-01-03 08:56 UTC, yunju2 commented
고친 것 
---
- controller단 test 코드 추가
- wildcard로 import된 거 삭제

2024-01-03 15:18 UTC, f-lab-lyan commented
일단 rebase 혹은 cherry-pick을 하셔서 conflict을 해결하셔야 할 것 같네요.

2024-01-04 13:04 UTC, f-lab-lyan commented on app/build.gradle
> +    id("io.freefair.lombok") version "8.4"
```suggestion
    id "io.freefair.lombok" version "8.4"
```

2024-01-09 13:59 UTC, yunju2 commented
### 고친 것

- build.gradle 수정
- 빌드패턴에서 생성자패턴으로 변경
- test code jsonpath에서 objectmapper로 변경
- 별점 매기기, 북마크 기능 api controller단 추가

2024-01-09 14:44 UTC, f-lab-lyan commented on app/src/test/java/com/jobhub/controller/BookmarkControllerTest.java
> +        input.add("isBookmark", "true");
`input`은 안 쓰이는 것이죠?

2024-01-10 06:08 UTC, yunju2 commented on app/src/test/java/com/jobhub/controller/BookmarkControllerTest.java
> +        input.add("isBookmark", "true");
input을 기대 response 값으로 해서 실제 response와 비교하는 로직으로 수정했습니다!

2024-01-11 13:23 UTC, f-lab-lyan commented on app/src/test/java/com/jobhub/controller/RatingControllerTest.java
> +        assertThat(actualResponse.getUserId()).isEqualTo(expectResponseBody.getFirst("userId"));
```suggestion
        assertThat(actualResponse.getUserId()).isEqualTo(testId);
```

2024-01-11 13:29 UTC, f-lab-lyan approved these changes
LGTM

2024-01-11 13:31 UTC, merged